### PR TITLE
spelling

### PR DESCRIPTION
**Pull request by bguiz**
- minimum --> minimum

### CODE REVIEW

**Comment by timdream** [comment]
Oops. 

We would have too change the typo in `wordcloud2.js` too, not just the documentation.

**Comment by bguiz** [comment]
Yes, that'd be a good idea!


W: http://bguiz.com

On 7 October 2015 at 13:53, Timothy Guan-tin Chien <notifications@github.com

**Comment by mibamur** [comment]
solution is here

**Comment by timdream** [comment]
Thank you both! Let's go with `min` instead.

**Pull request closed without merging**
