### PR TITLE
change commit info for git

### PR DESCRIPTION
**Pull request by yuhongda**

### CODE REVIEW

**Comment by timdream** [comment]
Hi! Could you mind explain what's the intention here? I see 0 line changes.

**Comment by yuhongda** [comment]
Hi there. I just changed email of the commits
 to related my GitHub account. :P

**Comment by yuhongda** [comment]
> Hi! Could you mind explain what's the intention here? I see 0 line changes.

Hi there. I just changed email of the commits
to related my GitHub account. :P

**Comment by timdream** [comment]
Your commits are correctly associated with your GitHub account: see https://github.com/timdream/wordcloud2.js/commits?author=yuhongda. In any case you can associate multiple e-mails to your GitHub account if you found your commits did not generate a link to your profile, anywhere on GitHub.

In any case, adding commits on top of commits won't change it, so "fixing" it over PR is not possible.

**Comment by yuhongda** [comment]
OK, I got it. Thanks~

**Comment by yuhongda** [comment]
> Your commits are correctly associated with your GitHub account: see https://github.com/timdream/wordcloud2.js/commits?author=yuhongda. In any case you can associate multiple e-mails to your GitHub account if you found your commits did not generate a link to your profile, anywhere on GitHub.
> 
> In any case, adding commits on top of commits won't change it, so "fixing" it over PR is not possible.

Ok, I got it. Thanks~

**Pull request closed without merging**
