### PR TITLE
fix touch events

### PR DESCRIPTION
**Pull request by maman**
sorry, the previous event detections aren't so reliable. this commit fixes that.

### CODE REVIEW

**Comment by timdream** [comment]
Ah, make sense. I should have caught it when review...

**Comment by timdream** [comment]
Maybe we need test cases for interactive stuff?

**Comment by maman** [comment]
yes, concur that.
any ideas how to test?

**Comment by timdream** [comment]
> yes, concur that.
> any ideas how to test?

Dispatch a `CustomEvent` instance on the canvas DOM element, with the mouse/touch event naming and with properties set by ourselves. Should work, though the call go through the real DOM. If `canvas.dispatchEvent()` stop us from abusing it like that, we would need to expose the event handler functions somehow...

Thanks!

**Pull request merged**
