### PR TITLE
add a function to keep canvas from blurring when window resizing

### PR DESCRIPTION
**Pull request by qmark4444**
When resizing window, the words in canvas may get blurred, I add a function "keepScaling()' to keep them stay sharp.

### CODE REVIEW

**Comment by timdream** [comment]
Thanks for the pull request! I however not entire sure what you are trying to fix by looking at the code. Could you describe what you are trying to fix in detail perhaps by attach a step-to-reproduce?

**Comment by qmark4444** [comment]
Hi Timothy,

When zoom in a page, for example from 100% to 200%, the words in cloud
become blurred, or pixelated. So I suggest using window.devicePixelRatio to
scale the canvas to solve this problem.

Thank you,
Mark

**Comment by timdream** [comment]
Firefox is the only browser that reflects page zoom on devicePixelRatio,
according to bugzil.la/809788.

I don’t know if that the up-to-date information. If it is, adding something
that is only useful in Firefox provides little value comparing to the
future maintenance cost. I would prefer not to merge this pull request.

Let me know if you have more information to share.

(I don’t have an opinion on which browser is doing this correctly)

**Comment by ttqftech** [comment]
I think this merge request is worth more considering. The canvas render result is still burry by default even in 2026. I have to observe a wrapper div and double the canvas size and use the wrapper div to shrink it back. It's not a firefox relative problem, because most of users are using high DPI monitors now.

**Pull request closed without merging**
